# version: "3.9"
name: animanga
services:
  # ------------------- surrealdb ----------------------
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:v2.3.6
    restart: always
    entrypoint:
      - /surreal
      - start
      - --log
      - "trace"
      - --user
      - "root"
      - --pass
      - "root"
      - "--allow-all"
      - "file:/data/current.db"
    # command: ["start", "--log", "trace", "--auth", "--user", "root", "--pass", "root", "file:/data", "--allow-all"]
    # user: ":"
    tty: true
    volumes:
      - surrealdb_data:/data
    networks:
      - db
    ports:
      - "8000:8000"
  # ------------------- Meilisearch ----------------------
  # meilisearch:
  #   container_name: meilisearch
  #   image: getmeili/meilisearch:v1.5.1
  #   restart: always
  #   environment:
  #     - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
  #     - MEILI_DB_PATH=/data.ms
  #     - MEILI_ENV=development
  #   ports:
  #     - "7700:7700"
  #   volumes:
  #     - meilisearch_data:/data.ms
  #   networks:
  #     - db
  # ------------------- Redis ----------------------
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - db
    ports:
      - "6379:6379"
  # ------------------- api ----------------------
  # api:
  #   container_name: api
  #   build:
  #     context: ./animanga_api
  #     dockerfile: Dockerfile
  #   restart: always
  #   command: ./target/release/api
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - surrealdb
  #   volumes:
  #     - api_data:/api
  #   networks:
  #     - db
  #     - api
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"
  # ------------------- web ----------------------
  # www:
  #   container_name: www
  #   build:
  #     context: ./animanga_web
  #     dockerfile: Dockerfile
  #   restart: always    
  #   command: node .output/server/index.mjs
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - api
  #   volumes:
  #     - www_data:/web
  #   networks:
  #     - api
  #     - www
  #   ports:
  #     - "80:3000"
  #   expose:
  #     - "80"
# ------------------- Networks ----------------------
networks:
  db:
    driver: bridge
  api:
    driver: bridge
  www:
# networks:
#   default:
#     driver: bridge
# ------------------- Storage ----------------------
volumes:
  surrealdb_data:
  # meilisearch_data:
  redis_data:
  api_data:
  www_data:
