version: "3.9"
services:
  webserver:
    container_name: webserver
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
      - www_storage:/usr/local/etc/php/php.ini
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: main
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    #ports:
    #  - "3306:3306"
    volumes:
      - db_storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_password


volumes:
  db_storage:
  www_storage:
